sonar.projectKey=ifesdoc
sonar.projectName=IFESDOC
sonar.projectVersion=1.0.0

sonar.sourceEncoding=UTF-8
sonar.python.version=3.10

sonar.sources=backend/app,backend/pipeline_busca/src,backend/pipeline_indexador/src,interface-web/src
sonar.tests=backend/tests,backend/app/tests,backend/pipeline_indexador/src/tests,interface-web/src/test

sonar.test.inclusions=backend/tests/**/*.py,backend/app/tests/**/*.py,backend/pipeline_indexador/src/tests/**/*.py,interface-web/src/**/*.test.ts,interface-web/src/**/*.test.tsx,interface-web/src/**/*.spec.ts,interface-web/src/**/*.spec.tsx
sonar.exclusions=**/__pycache__/**,**/.pytest_cache/**,**/node_modules/**,**/dist/**,**/build/**,**/coverage/**,**/*.d.ts,interface-web/src/components/ui/**
sonar.cpd.exclusions=interface-web/src/components/ui/**

sonar.python.coverage.reportPaths=reports/coverage/backend-coverage.xml
sonar.javascript.lcov.reportPaths=reports/coverage/frontend/lcov.info
sonar.typescript.tsconfigPath=interface-web/tsconfig.json
